name: Build the Express Hello
run-name: ${{ gitea.actor }} is building Express Hello with Gitea Actions 🚀
on: [push]

jobs:
  Build-Express-Hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: NPM Install
        uses: actions/setup-node@v4
        with: 
          node-version: 20
      - run: npm install --loglevel=verbose
  Build-Express-Image:
    runs-on: ubuntu-latest
    needs: Build-Express-Hello
    if: gitea.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
        with:
          config-inline: |
            git.lab.unixnerd.org:5000
              http = true
              insecure = true
      - name: Build and push Docker image
        uses: https://github.com/docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "git.lab.unixnerd.org:5000/express-hello:${{gitea.sha}},git.lab.unixnerd.org:5000/express-hello:latest"

