name: Build the Express Hello
run-name: ${{ gitea.actor }} is building Express Hello with Gitea Actions 🚀
on: [push]

jobs:
  Build-Express-Hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ gitea.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by Gitea!"
      - run: echo "🔎 The name of your branch is ${{ gitea.ref }} and your repository is ${{ gitea.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ gitea.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ gitea.workspace }}
      - name: NPM Install
        uses: actions/setup-node@v4
        with: 
          node-version: 20
      - run: npm install --loglevel=verbose
  Build-Express-Image:
    runs-on: cth-ubuntu-latest
    needs: Build-Express-Hello
    if: gitea.ref == 'refs/heads/main'
    steps:
      - uses: https://github.com/actions/checkout@v4
      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
        with:
          config-inline: |
            git.lab.unixnerd.org:5000
              http = true
              insecure = false
      - name: Build and push Docker image
        uses: https://github.com/docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "git.lab.unixnerd.org:5000/express-hello:${{gitea.sha}},git.lab.unixnerd.org:5000/express-hello:latest"

