name: Build the Express Hello
run-name: ${{ gitea.actor }} is building Express Hello with Gitea Actions 🚀
on: [push]

jobs:
  Build-Express-Hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: NPM Install
        uses: actions/setup-node@v4
        with: 
          node-version: 20
      - run: npm install --loglevel=verbose
  Build-Express-Image-Gitea:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest
    needs: Build-Express-Hello
    if: gitea.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
      - name: Login to Gitea Registry
        uses: docker/login-action@v3
        with:
          registry: git.lab.unixnerd.org
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_PAT }}
      - name: Build and push Docker image
        uses: https://github.com/docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "ghcr.io/sholly/express-hello:latest,git.lab.unixnerd.org/sholly/express-hello:${{gitea.sha}},git.lab.unixnerd.org/sholly/express-hello:latest"

